# Q3
*Work with Numpy*<br>
In this notebook you're going to work with the numpy library to solve the problems<br>
Please follow the instructions and hints provided for each cell

## Part A

In [1]:
import numpy as np

In [2]:
def create_matrix(n):
  """
  In this function you should create matrix in order of n*n with random numbers 
  in the [n, n+100) interval.

  see the bellow link:
    https://numpy.org/doc/stable/reference/random/generated/numpy.random.randint.html

  Arguments:
    inputs:
      n: an integer describing the order of the matrix
    outputs:
      created matrix  
  """
  ##############################################
  ############ YOUR CODES GO HERE ##############
  matrix = np.random.randint(n, n+100, size=(n, n))
  ##############################################

  return matrix

In [9]:
"""
In this cell you should get the input n and create the matrix by calling the function
Then print the matrix
"""
##############################################
############ YOUR CODES GO HERE ##############
print("please enter the n:")
n = int(input())
matrix = create_matrix(n)
# print matrix
print("matrix shape: ")
print(matrix.shape)
print("matrix values")
print(matrix)
##############################################

please enter the n:
matrix shape: 
(5, 5)
matrix values
[[ 44  13  70  35  84]
 [ 83  56  37  97  93]
 [ 81  96   7 100  76]
 [ 10  98  34  35  57]
 [ 76   9  62  55  77]]


In [18]:
def count_digits(matrix):
  """
  In this function you should implement a routine to count the digits in the given matrix.

  Arguments:
    inputs:
      matrix: input matrix
    outputs:
      digits: a dictionary containing digits as its keys and the counted numbers as its value
  """

  ##############################################
  ############ YOUR CODES GO HERE ##############
  digits = {}
  for dig in range(10):
    digits[dig] = 0
  matrix_shape = matrix.shape
  for i in range(matrix_shape[0]):
    for j in range(matrix_shape[1]):
      num = matrix[i][j]
      # https://stackoverflow.com/questions/21270320/turn-a-single-number-into-single-digits-python#:~:text=Use%20str%20to%20convert%20the,the%20digits%20back%20into%20integers.
      for digit_as_str in str(num):
        digit = int(digit_as_str)
        # if digit in digits:
        #   digits[digit] += 1
        # else:
        #   digits[digit] = 1
        digits[digit] += 1

  ##############################################

  return digits


In [19]:
"""
In this cell call the implemented function and print the result
"""


##############################################
############ YOUR CODES GO HERE ##############
digits = count_digits(matrix)
print(digits)
##############################################

{0: 4, 1: 4, 2: 1, 3: 7, 4: 4, 5: 6, 6: 5, 7: 9, 8: 4, 9: 5}


## Part B

In [34]:
def traverse_matrix(matrix):
  """
  Traverse the input matrix in the given manner then print result

  Arguments:
    inputs:
      matrix: input matrix
    outputs
  """

  ##############################################
  ############ YOUR CODES GO HERE ##############
  res = []

  matrix_shape = matrix.shape
  n = matrix_shape[0]
  for diameter in range(0, 2*n-2+1):
    if (diameter % 2 == 1):
      for row in range(max(0, diameter-n), min(n, diameter+1)):
        col = diameter - row
        if col >= n:
            continue
        # print(matrix[row,col])
        # print(f"row: {row}, col: {col}")
        res.append(matrix[row, col])
    else:
      for col in range(max(0, diameter-n), min(n, diameter+1)):
        row = diameter - col
        if row >= n:
            continue
        # print(matrix[row,col])
        # print(f"row: {row}, col: {col}")
        res.append(matrix[row, col])
  return res
  ##############################################

In [37]:
result = traverse_matrix(matrix)
print(matrix)
print(result)
for res in result:
    print(res)
#print output

[[ 44  13  70  35  84]
 [ 83  56  37  97  93]
 [ 81  96   7 100  76]
 [ 10  98  34  35  57]
 [ 76   9  62  55  77]]
[44, 13, 83, 81, 56, 70, 35, 37, 96, 10, 76, 98, 7, 97, 84, 93, 100, 34, 9, 62, 35, 76, 57, 55, 77]
44
13
83
81
56
70
35
37
96
10
76
98
7
97
84
93
100
34
9
62
35
76
57
55
77
