# Q4

## Part A

In [3]:
"""
Please define the mentioned matrices and the operations

consider the bellow links:
https://numpy.org/doc/stable/reference/generated/numpy.transpose.html

https://numpy.org/doc/stable/reference/generated/numpy.dot.html

"""
import numpy as np

##############################################
############ YOUR CODES GO HERE ##############
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
transposed_A = A.transpose()
B = np.array([[1], [-1], [1]])
# print(A)
# print(transposed_A)
# print(B)
M1 = np.linalg.inv(np.dot(transposed_A, A))
# M1 = np.linalg.inv(np.matmul(transposed_A, A))
# M1 = np.linalg.inv(transposed_A @ A)
# print(M1)
M2 = np.dot(np.dot(M1, transposed_A),B)
# M2 = np.matmul(np.matmul(M1, transposed_A),B)
# M2 = (M1 @ transposed_A) @ B
# print(M2)
M3 = M2 + A
# M3 = np.add(M2,A)
print(M3)
##############################################

[[0.796875 1.796875 2.796875]
 [4.       5.       6.      ]
 [7.203125 8.203125 9.203125]]


## Part B

In [12]:
def window_sliding(A, B):

  """
  In this function you should implement the sliding window method

  Arguments:
    inputs:
      A: a matrix of 3*3 order for treating as the window
      B: a matrix of 5*5 order for treating as the input matrix
    outputs:
      res: resulting matrix of the sliding window 
  """

  # C = np.convolve(A, B, 'valid')
  # print(C)
  ##############################################
  ############ YOUR CODES GO HERE ##############
  A_shape = A.shape
  B_shape = B.shape
  res = np.zeros((B_shape[0] - A_shape[0] + 1, B_shape[1] - A_shape[1] + 1))
  for row in range(res.shape[0]): # slide the window over the input matrix B. 
    for col in range(res.shape[1]):
      element = np.sum(A * B[row:row+A_shape[0], col:col+A_shape[1]]) # calculate the sum of element-wise multiplication of A and B[row:row+2, col:col+2]. 
      # element = np.sum(np.dot(A, B[row:row+A_shape[0], col:col+A_shape[1]])) # calculate the sum of element-wise multiplication of A and B[row:row+2, col:col+2]. 
      res[row, col] = element
  
  ##############################################
  # res = np.lib.stride_tricks.sliding_window_view(B, A.shape)

  return res

In [13]:
A = np.array([[1,1,1],[1,-9,1],[1,1,1]])
B = np.array([[1,1,1,1,1],[1,2,2,2,1],[1,2,2,2,1],[1,2,2,2,1],[1,1,1,1,1]])
print(window_sliding(A, B))

[[-7. -5. -7.]
 [-5. -2. -5.]
 [-7. -5. -7.]]
